### ISSUE TITLE
File logging may not complete if the process ends too quickly

### ISSUE THREAD

**Issue by thelollies** [LoyaltyNZ/hoodoo#123]
When reporting logs via Hoodoo::Logger::StreamWriter, log entries which are in the process of being written to file sometimes do not make it to the file if the main process completes too fast.

**Comment by thelollies** [comment]
Same goes for exception reporting via Airbrake.

**Comment by pond** [comment]
Exception reporters and loggers both work off communication pools and the pool system provides a `wait` method to use in case there are any threaded workers which need to shut down.

```
Hoodoo::Services::Middleware::ExceptionReporting.wait()
Hoodoo::Services::Middleware::logger.wait()

custom_logger = Hoodoo::Logger.new
# ...
custom_logger.wait()
```

**Comment by thelollies** [comment]
That's working perfectly, thanks.
