### ISSUE TITLE
Loss of caller version key in memcached may result in invalid sessions

### ISSUE THREAD

**Issue by grahamjenson** [LoyaltyNZ/hoodoo#98]
This line https://github.com/LoyaltyNZ/hoodoo/blob/a6cc8fb33b8dcd62b25ec783b8909bcf2ff8c30e/lib/hoodoo/services/services/session.rb#L178 writes a caller version to memcached when it saves a session. Without this memcached may remove a caller key which would permanently invalidate all sessions created by the caller.

Adding a comment, and a test to ensure this behaviour is a requirement of saving a session would be useful to make sure that this line is never optimised out of the code.

**Comment by pond** [comment]
Addressed by #197, which adds commentary explaining what's going on and how come sessions stay valid. Additional session workflow and edge case test coverage introduced by that set of changes should prevent regression.
